version: '3.4'

services:

  moderator:
    image: moderator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    # ports:
    #   - "3000:3000"
    network_mode: "host"  # FIXME:
    depends_on:
      - redis


  redis:
    image: redis:7.0.4
    platform: linux/arm64
    ports:
      - "6379:6379"
    network_mode: "host"  # FIXME:
