version: 2.1

jobs:
  setup-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
  test:
    docker:
      - image: cimg/node:16.16.0
      - image: cimg/redis:7.0.4
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install --force  # どうにかしないと
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm test
  doc:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          name: Configure git
          command: |
            git config user.email "tanacchi+circleci@users.noreply.github.com"
            git config user.name "tanacchi+circleci"
      - run:
          name: Update docs
          command: |
            npm install --force
            npm run doc
      - run:
          name: Install gh-pages
          command: npm install -g --silent gh-pages
      - run:
          name: Deploy document
          command: gh-pages --dotfiles --message "[skip ci] Update document" --dist docs


workflows:
  deploy:
    jobs:
      - test
      - setup-docker
      - doc

