version: 2.1

jobs:
  run:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

workflows:
  deploy:
    jobs:
      - run

